task:
  name: FreeBSD
  alias: test-freebsd
  env:
    MAKE_FLAGS: -j 8

  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y cgal gmp mpfr boost-libs cmake ninja

  build_script:
    - export CGAL_VERSION=6.0.1
    - fetch "https://github.com/CGAL/cgal/releases/download/v${CGAL_VERSION}/CGAL-${CGAL_VERSION}.tar.xz" -o CGAL-${CGAL_VERSION}.tar.xz
    - tar xJf CGAL-${CGAL_VERSION}.tar.xz
    - cmake -GNinja -S . -B build -DSFCGAL_BUILD_TESTS=ON -DCGAL_DIR=CGAL-${CGAL_VERSION}
    - cmake --build build
    - ctest -VV --test-dir build
  freebsd_instance:
    cpu: 8
    memory: 24g
  matrix:
    - name: 15.0-CURRENT
      freebsd_instance:
        image_family: freebsd-15-0-snap
    - name: 14.1-RELEASE
      freebsd_instance:
        image_family: freebsd-14-1
    - name: 13.3-RELEASE
      freebsd_instance:
        image_family: freebsd-13-3

task:
  name: macOS
  alias: test-macos
  test_script:
    - brew update
    - brew install cmake boost cgal gmp mpfr
    - cmake -DSFCGAL_BUILD_TESTS=ON -S . -B build
    - cmake --build build
    - ctest -VV --test-dir build
  matrix:
    macos_instance:
      image: ghcr.io/cirruslabs/macos-ventura-base:latest
    macos_instance:
      image: ghcr.io/cirruslabs/macos-ventura-base:latest
