task:
  name: FreeBSD
  alias: test-freebsd
  env:
    MAKE_FLAGS: -j 8

  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
    - pkg install -y cgal gmp mpfr boost-libs cmake ninja

  build_script:
    - mkdir build
    - cmake -DSFCGAL_BUILD_TESTS=ON
    - make $(MAKE_FLAGS)
    - ctest -VV
  freebsd_instance:
    cpu: 8
    memory: 24g
  matrix:
    - name: 14-CURRENT
      freebsd_instance:
        image_family: freebsd-14-0-snap
    - name: 13.0-RELEASE
      freebsd_instance:
        image_family: freebsd-13-0
    - name: 12.3-RELEASE
      freebsd_instance:
        image_family: freebsd-12-3

task:
  name: macOS
  alias: test-macos
  test_script:
    - brew update
    - brew install cmake boost cgal gmp mpfr
    - cmake -DSFCGAL_BUILD_TESTS=ON -S . -B build
    - cmake --build build
    - ctest --test-dir build
  matrix:
    macos_instance:
      image: big-sur-base
    macos_instance:
      image: monterey-base
