# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# Don't run pre-commit on files under third-party/
exclude: "^\
  (third-party/.*)\
  "

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files # prevents giant files from being committed.
        args: ["--maxkb=1200"]
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems.
      - id: check-merge-conflict # checks for files that contain merge conflict strings.
      - id: check-yaml # checks yaml files for parseable syntax.
      - id: detect-private-key # detects the presence of private keys.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
        exclude: ^test/data
      - id: fix-byte-order-marker # removes utf-8 byte order marker.
      - id: mixed-line-ending # replaces or checks mixed line ending.
      - id: requirements-txt-fixer # sorts entries in requirements.txt.
      - id: trailing-whitespace # trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        args: ["--style=file", "-i"]  # Use the .clang-format file for configuration and apply all fixes
        files: ^src/.*\.(c|h|cpp|hpp)$

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args:
          [
            "--config",
            ".markdownlint.json",
            "--ignore-path",
            ".markdownlintignore",
            "--fix",
          ]
        language: node
        pass_filenames: true
        files: ^website/.*
        types:
          - file
          - markdown
          - non-executable

  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: v1.3.5
  #   hooks:
  #     - id: clang-tidy
  #       files: (src|tests)/.*\.(c|h|cpp|hpp)$

  # - id: cppcheck
  #   name: cppcheck
  #   entry: cppcheck
  #   language: system
  #   args:
  #     [
  #       --enable=all,
  #       --suppress=unusedFunction,
  #       --suppress=unmatchedSuppression,
  #       --suppress=missingIncludeSystem,
  #       --suppress=toomanyconfigs,
  #       --error-exitcode=1,
  #       --language=c++,
  #     ]
  #   files: \.(c|h|cpp|hpp)$
