// Copyright (c) 2025-2025, SFCGAL team.
// SPDX-License-Identifier: LGPL-2.0-or-later

#include "SFCGAL/version.h"
#include <boost/test/unit_test.hpp>

BOOST_AUTO_TEST_SUITE(SFCGAL_VersionTest)

BOOST_AUTO_TEST_CASE(testMakeVersion)
{
  BOOST_CHECK_EQUAL(SFCGAL_MAKE_VERSION(1, 4, 1), SFCGAL_MAKE_VERSION(1, 4, 1));
  BOOST_CHECK_EQUAL(SFCGAL_MAKE_VERSION(3, 0, 0), SFCGAL_MAKE_VERSION(3, 0, 0));
  BOOST_CHECK_EQUAL(SFCGAL_MAKE_VERSION(3, 1, 0), SFCGAL_MAKE_VERSION(3, 1, 0));

  BOOST_CHECK(SFCGAL_MAKE_VERSION(1, 4, 0) < SFCGAL_MAKE_VERSION(1, 4, 1));
  BOOST_CHECK(SFCGAL_MAKE_VERSION(1, 2, 0) < SFCGAL_MAKE_VERSION(1, 4, 1));
  BOOST_CHECK(SFCGAL_MAKE_VERSION(1, 2, 2) < SFCGAL_MAKE_VERSION(1, 4, 1));

  BOOST_CHECK(SFCGAL_MAKE_VERSION(2, 0, 0) > SFCGAL_MAKE_VERSION(1, 40, 8));
  BOOST_CHECK(SFCGAL_MAKE_VERSION(2, 0, 0) > SFCGAL_MAKE_VERSION(0, 16, 5));
}

BOOST_AUTO_TEST_SUITE_END()
