/**
 * SFCGAL WebAssembly Module Loader
 * Auto-generated by scripts/generate-lib.sh
 */

let sfcgalInstance = null;

/**
 * Load and initialize the SFCGAL WebAssembly module
 * @returns {Promise<Object>} The SFCGAL instance with all methods
 */
export async function loadSFCGAL() {
    if (sfcgalInstance) {
        return sfcgalInstance;
    }

    try {
        const SFCGALModule = await import('../sfcgal.js');
        const Module = await SFCGALModule.default();

        // Create SFCGAL instance
        const sfcgalClass = new Module.SFCGAL();
        sfcgalClass.initialize();

        sfcgalInstance = sfcgalClass;
        return sfcgalInstance;
    } catch (error) {
        console.error('Failed to load SFCGAL module:', error);
        throw new Error(`Failed to load SFCGAL: ${error.message}`);
    }
}

/**
 * Display a status message
 */
export function showStatus(elementId, message, type = 'info') {
    const element = document.getElementById(elementId);
    if (!element) return;

    element.textContent = message;
    element.className = 'status';

    if (type === 'success') {
        element.classList.add('status-success');
        setTimeout(() => { element.style.display = 'none'; }, 3000);
    } else if (type === 'error') {
        element.classList.add('status-error');
    } else {
        element.classList.add('status-info');
    }
}

export function getSFCGAL() {
    return sfcgalInstance;
}
