name: SonarCloud

on:
  push:
    branches:
      - master
      - develop
      - features/*
      - feature/*
      - fix/*
      - release/*

jobs:
  sonarcloud:
    name: SonarCloud

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    env:
      SONAR_SCANNER_VERSION: 4.7.0.2747 # Find the latest version in the "Linux" link on this page:
      # https://sonarcloud.io/documentation/analysis/scan/sonarscanner/
      SONAR_SERVER_URL: "https://sonarcloud.io"
      LANG: "en_US.UTF-8"

    steps:
    
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages and analysis
        uses: actions/cache@v2
        id: sonarcloud-cache
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-${{env.GITHUB_REF_NAME}}-cache

      - name: Download and setup sonar-scanner
        shell: bash
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
        if: steps.sonarcloud-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }}
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          
      - name: Download and setup build-wrapper
        shell: bash
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-linux-x86.zip
        if: steps.sonarcloud-cache.outputs.cache-hit != 'true'
        run: |
          curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
          unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
          
      - name: Set build-wrapper and sonar-scanner paths
        run: |
          echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH
          echo "$HOME/.sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux/bin" >> $GITHUB_PATH

      - name: Configure
        run: |
          cmake -B build -DSFCGAL_BUILD_TESTS=ON
      - name: Build
        run: |
          build-wrapper/build-wrapper-linux-x86-64 --out-dir bw-output cmake --build build/ --config Release

      - name: Run sonar-scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          locale-gen "${{env.LANG}}"
          update-locale LC_ALL="${{env.LANG}}"
          export LANG="${{env.LANG}}"
          sonar-scanner -Dsonar.host.url="${SONAR_HOST_URL}" -Dsonar.token="${SONAR_TOKEN}" -Dsonar.cfamily.build-wrapper-output=bw-output --define sonar.cfamily.cache.path=$HOME/.sonar/cache

